name: "Vercel Preview Alias"
description: "Alias Vercel Preview URLs"
inputs:
  vercel-token:
    description: "Vercel token e.g. https://vercel.com/account/tokens"
    required: true
  vercel-preview-url:
    required: true
    description: "Preview URL that you want to alias. If you have Vercel GitHub App, it's in the GitHub event e.g. github.event.deployment_status.target_url"
  vercel-target-url:
    required: true
    description: "Target URL that you want e.g. beta.example.com"
  vercel-scope:
    required: false
    description: "If in a Team, the scope of the team"
  vercel-preview-url-env-var:
    required: false
    description: "If provided, the `vercel-target-url` will be stored in this env var for the current branch in Vercel"
  vercel-preview-url-env-var-branch:
    required: false
    description: "If `vercel-preview-url-env-var` is provided then this must also. Should be the branch on which we will apply the env var in Vercel. (e.g feature/xxx or some-branch)"
outputs:
  success:
    description: "Is true if the aliasing is successful"
runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "triangle"
  color: "white"
